spring:
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdnc:mysql://localhost:3306/rest_com_springboot?useTimezone=true&serverTimezone=UTC
      username: root
      password: admin